name: Export draw.io svgs

on:
  push:
    paths:
      - '**/*.drawio'

jobs:
  exports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List draw.io files
        run: |
          echo "Looking for .drawio files..."
          find . -name '*.drawio'

      - name: Export draw.io files to SVG (Docker, embedded XML)
        run: |
          files=$(find . -name '*.drawio')
          if [ -z "$files" ]; then
            echo "No .drawio files found, skipping export."
            exit 0
          fi

          for file in $files; do
            echo "Processing $file"
            docker run --rm -v $PWD:/data jgraph/drawio \
              --export --format svg --embed-diagram \
              --output "/data/${file%.drawio}.svg" "/data/$file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update exported SVGs" || echo "No changes to commit"
          git push

